export const usersData = [
  {
    id: 0,
    name: "Safwat",
    checkedIn: "11:00",
    checkedOut: "16:30",
    actions: "actions",
  },
  {
    id: 1,
    name: "Khaled",
    checkedIn: "11:00",
    checkedOut: "12:30",
    actions: "actions",
  },
  {
    id: 2,
    name: "Ali",
    checkedIn: "11:00",
    checkedOut: "10:30",
    actions: "actions",
  },
  {
    id: 3,
    name: "Bahy",
    checkedIn: "10:00",
    checkedOut: "16:00",
    actions: "actions",
  },
  {
    id: 4,
    name: "Nabil",
    checkedIn: "01:00",
    checkedOut: "--",
    actions: "actions",
  },
  {
    id: 5,
    name: "Sara",
    checkedIn: "00:00",
    checkedOut: "--",
    actions: "actions",
  },
  {
    id: 6,
    name: "Eman",
    checkedIn: "11:00",
    checkedOut: "17:00",
    actions: "actions",
  },
  {
    id: 7,
    name: "Mona",
    checkedIn: "11:00",
    checkedOut: "--",
    actions: "actions",
  },
  {
    id: 8,
    name: "Reda",
    checkedIn: "03:00",
    checkedOut: "--",
    actions: "actions",
  },
  {
    id: 9,
    name: "Nour",
    checkedIn: "08:00",
    checkedOut: "--",
    actions: "actions",
  },
  {
    id: 10,
    name: "Sharaf",
    checkedIn: "05:00",
    checkedOut: "20:00",
    actions: "actions",
  },
];
